### ISSUE TITLE
Search does not adhere to Joplin syntax

### ISSUE THREAD

**Issue by Grydpype** [BeatLink/Joplin-Agenda-Plugin#1]
I don't know if this plugin is still being maintained, but if it is I think the implementation of the search is not entirely correct.

According to the Joplin search syntax an expression such as _any:1 tag:foo tag:bar_ should be permitted and deliver objects containing either the tag _foo_ or the tag _bar_, whereas _any:0 tag:foo tag:bar_ should return objects containing both _foo_ and _bar_.

In case of any:1 this is not what is happening in the agenda panel; instead, using any:1 returns every todo, regardless of the tag.

**Comment by adva-cg** [comment]
Hello. 'Search Criteria' field is not saved if it contains Unicode characteristics. If edit file 'profiles.sqlite3' then filter work correctly but it is not edited from gui.

**Comment by BeatLink** [comment]
Closed by https://github.com/BeatLink/Joplin-Agenda-Plugin/pull/2
